<?php

namespace TelegramBotEssentials\Campaigns\Telegram\Forms;

use TelegramBotEssentials\Campaigns\Models\Campaign;
use TelegramBotEssentials\Campaigns\Telegram\Features\Admin\CampaignsFeature;
use TelegramBotEssentials\Essence\Enums\Roles;
use TelegramBotEssentials\Essence\Forms\Form;
use TelegramBotEssentials\Essence\Forms\Steps\Text;
use TelegramBotEssentials\Essence\Telegram\TelegramResponse;

/**
 * Creates a campaign. Nothing is written until the admin confirms the
 * summary, so an abandoned form leaves nothing behind. The link code is
 * generated by the model, never asked for.
 */
class CreateCampaignForm extends Form
{
    protected string $type = 'CAMPAIGN_CREATE';

    protected int $perm = Roles::ADMIN->value;

    protected string $lang = 'tbe-campaigns::campaigns.wizard';

    public function steps(): array
    {
        return [
            Text::make('name')
                ->rules(['min:2', 'max:60']),

            Text::make('days')
                ->skippable()
                ->rules(['integer', 'min:1', 'max:3650'])
                ->hint(__('tbe::forms.hints.integer')),
        ];
    }

    public function onComplete(array $answers, array $ctx): TelegramResponse
    {
        $name = $answers['name'] ?? null;
        $days = $answers['days'] ?? null;

        $campaign = Campaign::create([
            'bot_id' => wHook()->bot()->id,
            'name' => is_string($name) ? $name : '',
            'expires_at' => is_numeric($days) ? now()->addDays((int) $days) : null,
        ]);

        return CampaignsFeature::show($campaign, $this->lastPage($ctx));
    }

    /** The list, refreshed so the new campaign shows at the top of its first page. */
    public function originalScreen(array $ctx): ?TelegramResponse
    {
        return CampaignsFeature::menu(1);
    }

    /** @param  array<string, mixed>  $ctx */
    private function lastPage(array $ctx): int
    {
        $lastPage = $ctx['lastPage'] ?? 1;

        return max(1, is_numeric($lastPage) ? (int) $lastPage : 1);
    }
}
